# Generated by Django 5.1.7 on 2025-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_curso_alter_usuario_matricula_usuario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_matéria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
