# Generated by Django 5.1.7 on 2025-04-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_curso_nome_matéria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
    ]
