# Generated by Django 5.1.7 on 2025-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_gradehoraria_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
