# Generated by Django 5.1.7 on 2025-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_registroacesso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradehoraria',
            name='disciplina',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
