# Generated by Django 5.1.7 on 2025-05-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_face', '0001_initial'),
        ('gestor', '0002_curso_gradehoraria_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.curso'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
