# Generated by Django 5.1.7 on 2025-05-27 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_curso_alter_gradehoraria_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradehoraria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 27, 12, 37, 5, 294611, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
