# Generated by Django 5.1.7 on 2025-05-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_face', '0004_alter_usuario_curso_delete_curso'),
        ('gestor', '0009_rename_curso_id_gradehoraria_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacesso',
            name='horario_saida',
        ),
        migrations.RemoveField(
            model_name='registroacesso',
            name='nome',
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro_face.usuario'),
            preserve_default=False,
        ),
    ]
